
services:
  # Servicio para el backend (Node.js)
  backend:
    image: galbino/consultorio-pediatrico:v0.1.3
    container_name: backend-consultorio
    restart: always
    ports:
      - "3000:3000"
    networks:
      - consultorio_network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:16.6-alpine3.21
    container_name: consultorio-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D3v310p34*DF$
      POSTGRES_DB: consultorio-pediatrico
    ports:
      - "5432:5432"
    networks:
      - consultorio_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql

  # Servicio para el frontend (React, Angular, etc.)
  frontend:
    image: galbino/consultorio-pediatrico-frontend:v0.1.3
    container_name: frontend-consultorio
    restart: always
    ports:
      - "8383:80"
    networks:
      - consultorio_network
    depends_on:
      - backend

networks:
  consultorio_network:
    driver: bridge

volumes:
  pgdata:
